### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by lormayna** [pauloromeira/onegram#8]
Hi,
if I tried to login, I got this error:

`Traceback (most recent call last):
  File "main.py", line 33, in <module>
    for p in explore(tag='bacchereto'):
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/sessionlib/sessionlib.py", line 144, in wrapped
    current_session = cls.current()
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/onegram/session.py", line 31, in current
    return Session.current() or login()
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/onegram/session.py", line 221, in login
    return Login(*args, **kwargs).open()
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/sessionlib/sessionlib.py", line 92, in open
    context = enter_contexts.send(context_obj)
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/onegram/session.py", line 168, in enter_contexts
    self._login()
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/onegram/session.py", line 185, in _login
    headers['X-CSRFToken'] = self.cookies['csrftoken']
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/lorenzo/project/instabot/lib/python3.6/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`

**Comment by neFAST** [comment]
Same error here, it stopped working 2 or 3 days ago

**Comment by neFAST** [comment]
Some clues here: https://github.com/instabot-py/instabot.py/issues/1287

**Comment by pauloromeira** [comment]
This issue is solved. Please update onegram to get the fix:
```sh
pip install -U onegram
```
